-- ============================================================================
-- TUT Vision — Database Schema (Phase 1)
-- ----------------------------------------------------------------------------
-- Staff-availability platform for Tshwane University of Technology.
-- PostgreSQL. Identity comes from Microsoft Entra (no passwords stored here).
--
-- HOW TO RUN (PowerShell), against the tut_vision database:
--     psql -U postgres -d tut_vision -f schema.sql
--
-- Tables are created in dependency order (parents before children) so that
-- every foreign key points at a table that already exists.
--
-- NOTE ON POPIA: raw GPS coordinates and lobby photos are never stored. We keep
-- only the on/off-campus flag and an encrypted biometric template. See the
-- geofence and biometric_enrolment sections below.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- Teardown (rebuild-from-scratch only).
-- These DROPs delete the tables AND ALL THEIR DATA. CASCADE removes anything
-- that depends on them, so order does not matter here. Leave this block
-- commented out during normal use; uncomment only when you deliberately want
-- to wipe and rebuild the whole database.
-- ----------------------------------------------------------------------------
-- DROP TABLE IF EXISTS lobby_device        CASCADE;
-- DROP TABLE IF EXISTS biometric_enrolment CASCADE;
-- DROP TABLE IF EXISTS geofence            CASCADE;
-- DROP TABLE IF EXISTS device              CASCADE;
-- DROP TABLE IF EXISTS follow              CASCADE;
-- DROP TABLE IF EXISTS consultation_slot   CASCADE;
-- DROP TABLE IF EXISTS status_message      CASCADE;
-- DROP TABLE IF EXISTS status_state        CASCADE;
-- DROP TABLE IF EXISTS users               CASCADE;
-- DROP TABLE IF EXISTS department          CASCADE;
-- DROP TABLE IF EXISTS faculty             CASCADE;
-- DROP TABLE IF EXISTS campus              CASCADE;


-- ============================================================================
-- 1. Organisational hierarchy: campus -> faculty -> department
--    Small, stable lookup tables. Integer keys are fine (internal use only).
-- ============================================================================

CREATE TABLE campus (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE faculty (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id   integer NOT NULL REFERENCES campus(id),
    name        text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
    -- Later refinement: name should be UNIQUE within a campus, i.e.
    -- UNIQUE (campus_id, name) -- deferred to the refining pass.
);

CREATE TABLE department (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_id  integer NOT NULL REFERENCES faculty(id),
    name        text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);


-- ============================================================================
-- 2. Users — the hub. Almost everything hangs off a person.
--    UUID key: user ids leak into URLs/apps, so they must not be guessable.
--    No password column: Microsoft Entra is the sole identity provider.
--    department_id is nullable: a user may sign in before we know their dept.
-- ============================================================================

CREATE TABLE users (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    microsoft_oid  text NOT NULL UNIQUE,
    name           text NOT NULL,
    email          text NOT NULL UNIQUE,
    role           text NOT NULL CHECK (role IN ('staff', 'student')),
    department_id  integer REFERENCES department(id),
    created_at     timestamptz NOT NULL DEFAULT now()
    -- Kept normalised: faculty/campus are reachable via department, so they
    -- are not duplicated here. Add denormalised shortcuts only if real queries
    -- prove too slow ("normalise first, optimise later, with evidence").
);


-- ============================================================================
-- 3. Status — a person's live state.
--    status_state  = ONE-TO-ONE (exactly one current status per user).
--    status_message = ONE-TO-MANY (a user posts many messages over time).
-- ============================================================================

-- user_id is BOTH primary key AND foreign key -> enforces one-to-one.
CREATE TABLE status_state (
    user_id          uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    availability     text NOT NULL DEFAULT 'unavailable'
                     CHECK (availability IN ('available', 'busy', 'unavailable')),
    presence         text NOT NULL DEFAULT 'off_campus'
                     CHECK (presence IN ('on_campus', 'off_campus')),
    presence_source  text NOT NULL DEFAULT 'manual'
                     CHECK (presence_source IN ('geofence', 'facial', 'manual')),
    manual_override  boolean NOT NULL DEFAULT false,
    updated_at       timestamptz NOT NULL DEFAULT now()
    -- Planned addition for precedence logic: override_expires_at timestamptz.
);

-- Separate id key; user_id is a plain (repeatable) FK -> one-to-many.
CREATE TABLE status_message (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    text        text NOT NULL,
    active      boolean NOT NULL DEFAULT true,
    expires_at  timestamptz,             -- nullable: message may never expire
    created_at  timestamptz NOT NULL DEFAULT now()
);


-- ============================================================================
-- 4. Consultation schedule — recurring weekly availability windows.
--    'time' stores time-of-day only; the weekday lives in day_of_week.
--    Convention: day_of_week 0 = Sunday .. 6 = Saturday (matches Postgres DOW).
-- ============================================================================

CREATE TABLE consultation_slot (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    day_of_week  integer NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
    start_time   time NOT NULL,
    end_time     time NOT NULL,
    recurring    boolean NOT NULL DEFAULT true,
    created_at   timestamptz NOT NULL DEFAULT now(),
    CHECK (end_time > start_time)        -- table-level: compares two columns
);


-- ============================================================================
-- 5. Follow — MANY-TO-MANY between students and staff (a join table).
--    Both FKs point at the same table (users); the column names carry the role.
--    UNIQUE (student_id, staff_id): a student can't follow the same staff twice.
--    Per-follow notify flags live here because they belong to the relationship.
-- ============================================================================

CREATE TABLE follow (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id           uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    staff_id             uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    notify_state_changes boolean NOT NULL DEFAULT false,
    notify_messages      boolean NOT NULL DEFAULT true,
    created_at           timestamptz NOT NULL DEFAULT now(),
    UNIQUE (student_id, staff_id)
);


-- ============================================================================
-- 6. Devices — a user's phones/browsers for push + geofencing.
--    geofence_enabled defaults false: geofencing is explicitly opt-in (GEO-4).
--    push_token nullable: device may exist before notification permission.
-- ============================================================================

CREATE TABLE device (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform         text NOT NULL CHECK (platform IN ('ios', 'android', 'web')),
    push_token       text,
    geofence_enabled boolean NOT NULL DEFAULT false,
    created_at       timestamptz NOT NULL DEFAULT now()
);


-- ============================================================================
-- 7. Geofence — a campus boundary as a centre point + radius (metres).
--    Only the DEFINITION is stored here (plain numbers) — no PostGIS needed.
--    PostGIS is added later for the QUERY side ("is this device inside a fence?").
-- ============================================================================

CREATE TABLE geofence (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id   integer NOT NULL REFERENCES campus(id) ON DELETE CASCADE,
    latitude    double precision NOT NULL,
    longitude   double precision NOT NULL,
    radius_m    integer NOT NULL CHECK (radius_m > 0),
    created_at  timestamptz NOT NULL DEFAULT now()
);


-- ============================================================================
-- 8. Biometric enrolment — POPIA-sensitive (special personal information).
--    template is an ENCRYPTED derived template (bytea), never a photo.
--    Encryption happens BEFORE the value reaches this column.
--    consent_given_at / consent_withdrawn_at form a consent audit trail;
--    'active' lets a user withdraw without hard-deleting the consent history.
-- ============================================================================

CREATE TABLE biometric_enrolment (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    template             bytea NOT NULL,
    consent_given_at     timestamptz NOT NULL DEFAULT now(),
    consent_withdrawn_at timestamptz,
    active               boolean NOT NULL DEFAULT true,
    created_at           timestamptz NOT NULL DEFAULT now()
    -- Later: enforce one active enrolment per user via a partial unique index.
);


-- ============================================================================
-- 9. Lobby device — the fixed facial-recognition kiosk per campus.
--    credential_hash: store a HASH of the kiosk's secret, never the secret.
-- ============================================================================

CREATE TABLE lobby_device (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id        integer NOT NULL REFERENCES campus(id) ON DELETE CASCADE,
    label            text NOT NULL,
    credential_hash  text NOT NULL,
    last_seen_at     timestamptz,
    created_at       timestamptz NOT NULL DEFAULT now()
);

-- End of schema.
